---- MODULE base ----
(* Generated by traceproof-poc — Phase 3 (Model Generation)
   Scenario: module-scoped: README
   Derived from knowledge files:
   - knowledge/README.md
   Generated: 2026-09-08T05:54:49+00:00
   Self-repair attempts this run: 0
   Note: structural fallback (no LLM key) — invariant bodies are placeholders
*)
EXTENDS Naturals, Sequences, TLC

CONSTANTS MaxSteps

VARIABLES pc, step

TypeOK ==
    /\ pc \in {"init", "running", "done", "error"}
    /\ step \in 0..MaxSteps

\* Source: knowledge/README.md — Concurrent access to shared state must be properly serialised.
Inv_Concurrent_access_to_shared_state_must_b == TRUE  \* TODO: replace with real predicate

Init ==
    /\ pc = "init"
    /\ step = 0

Next ==
    \/ /\ pc = "init"
       /\ pc' = "running"
       /\ step' = step
    \/ /\ pc = "running"
       /\ step < MaxSteps
       /\ pc' = "done"
       /\ step' = step + 1
    \/ /\ pc = "running"
       /\ step >= MaxSteps
       /\ pc' = "error"
       /\ step' = step

Spec == Init /\ [][Next]_<<pc, step>>

====
